### ISSUE TITLE
Build the pods and scene for the login functionallity

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/bar.io#15]
Just use material ui, it should look ok, but we won't go now for theming or style fine tunning, only bother about mobile layout.

![Screenshot 2020-11-27 at 08 25 40](https://user-images.githubusercontent.com/1457912/100422226-2f2c8900-308a-11eb-8ebb-3ccaf3896c5e.png)

Create a mock api service and implement validations and full flow

**Comment by Pdominguez15** [comment]
Should I implement the snackbar?

The login is mock but when the credentials are wrong, I show alert

**Comment by Pdominguez15** [comment]
Should I implement any test?

I have not implemented anything yet

**Comment by brauliodiez** [comment]
I would implement test on the loginValidation

you can open a separate case for this
