### ISSUE TITLE
Add Unit test support to dashboard common components

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/bar.io#25]
We have already them or applied to a similar code cut.

@Nasdan do you have available our dashboard specs? can you send it to @Pdominguez15 or point him where to find it?

**Comment by Nasdan** [comment]
Yes, I do. You have available this specs in [origin-front-admin](https://github.com/Lemoncode/origin-front-admin/tree/master/src/common/components/dashboard/components) repository.  @Pdominguez15, this specs are using the old way `getByTestId` as you know, it's better to use [this priority](https://testing-library.com/docs/guide-which-query/), if you want update it on this project.

**Comment by Pdominguez15** [comment]
@Nasdan I have the changes here  #26  When we merge with master, I can update the project origin [https://github.com/Lemoncode/origin-front-admin/tree/master/src/common/components/dashboard/components]
