### ISSUE TITLE
Create an special screen if super admin tries to login in bar admin

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/bar.io#58]
We are going to allow "superadmins" to edit any restaurant info.

When the user logs in:
- If he is a restaurant owner: his restaurant will be displayed (edit restaurant)
- If he is a "superadmin" (bario superadmin): a list of restaurants will appear, super admin will choose and will be able to edit that restaurant.

For this issue let's focus on the front aspect (later on we will go for backend implementation).
<img width="655" alt="Screenshot 2021-03-13 at 19 19 23" src="https://user-images.githubusercontent.com/1457912/111039931-09f13a00-8431-11eb-84aa-2e226081061d.png">

**Comment by Pdominguez15** [comment]
I see a superadmin scaffolding, but i dont see the login.

Do I have to implement the login?

Add dashboard or and after login add the list of restaurants?

@brauliodiez

**Comment by brauliodiez** [comment]
this is on normal admin not super admin
